
SCHEMA = {
    # Arithmetic
    'set'    : '{0} = {1}',
    'add'    : '{0} = {1} + {2}',
    'sub'    : '{0} = {1} - {2}',
    'mul'    : '{0} = {1} * {2}',
    'div'    : '{0} = {1} / {2}',
    'mod'    : '{0} = {1} % {2}',
    'pow'    : '{0} = {1} ** {2}',
    'abs'    : '{0} = abs({1})',
    'root'   : '{0} = {2} ** (1 / {1})',
    'log'    : '{0} = m.log({1}, {2})',
    'ln'     : '{0} = m.log({1})',
    'exp'    : '{0} = m.exp({1})',
    'fact'   : '{0} = m.factorial({1})',
    'flr'    : '{0} = m.floor({1})',
    'ceil'   : '{0} = m.ceil({1})',
    'rnd'    : '{0} = round({1})',
    'trnc'   : '{0} = m.trunc({1})',
    'min'    : '{0} = min({1}, {2})',
    'max'    : '{0} = max({1}, {2})',
    'rngflt' : '{0} = uniform({1}, {2})',
    'rngint' : '{0} = randint({1}, {2})',

    # Bitwise
    'and'    : '{0} = {1} & {2}',
    'or'     : '{0} = {1} | {2}',
    'xor'    : '{0} = {1} ^ {2}',
    'nand'   : '{0} = ((~({1}&{2}))&((1<<max({1},{2}).bit_length())-1))',
    'nor'    : '{0} = ((~({1}|{2}))&((1<<max({1},{2}).bit_length())-1))',
    'xnor'   : '{0} = ((~({1}^{2}))&((1<<max({1},{2}).bit_length())-1))',
    'shl'    : '{0} = {1} << {2}',
    'shr'    : '{0} = {1} >> {2}',
    'rol'    : '{0} = (({1} << {2}) & ((1 << (0 if {1} == 0 else m.floor(m.log(abs({1}), 2)) + 1)) - 1)) | ({1} >> ((0 if {1} == 0 else m.floor(m.log(abs({1}), 2)) + 1) - {2}))',
    'ror'    : '{0} = (({1} >> {2}) | ({1} << ((0 if {1} == 0 else m.floor(m.log(abs({1}), 2)) + 1) - {2}))) & ((1 << (0 if {1} == 0 else m.floor(m.log(abs({1}), 2)) + 1)) - 1)',
    'bitset' : '{0} = {1} | (1 << {2})',
    'bitclr' : '{0} = {1} & ~(1 << {2})',
    'bittog' : '{0} = {1} ^ (1 << {2})',
    'bitget' : '{0} = ({1} >> {2}) & 1',
    'bitson' : '{0} = bin({1}).count("1")',
    'bitlen' : '{0} = (0 if {1} == 0 else m.floor(m.log(abs({1}), 2)) + 1)',

    # Trig
    'sin' : '{0} = m.sin({1})',
    'cos' : '{0} = m.cos({1})',
    'tan' : '{0} = m.tan({1})',
    'csc' : '{0} = 1/m.sin({1})',
    'sec' : '{0} = 1/m.cos({1})',
    'cot' : '{0} = 1/m.tan({1})',

    # String
    'cast'     : '{0} = (float({1}) if "." in {1} else int({1})) if isinstance({1}, str) else str({1})',
    'len'      : '{0} = len({1})',
    'strsub'   : '{0} = {1}[{2}:{3}]',
    'strfind'  : '{0} = {1}.index({2})',
    'strsplit' : '{0}, {1} = {2}[{3}:], {2}[:{3}]',
    'strjoin'  : '{0} = {1} + {3} + {2}',
    'strrev'   : '{0} = {1}[::-1]',
    'strupper' : '{0} = {1}.upper()',
    'strlower' : '{0} = {1}.lower()',
    'strtrim'  : '{0} = {1}.lstrip().rstrip()',

    # Type checks
    'typeof'  : '{0} = type({1}).__name__',
    'isint'   : '{0} = int(isinstance({1}, int))',
    'isfloat' : '{0} = int(isinstance({1}, float))',
    'isstr'   : '{0} = int(isinstance({1}, str))',
    'isnone'  : '{0} = int(isinstance({1}, None))',

    # Control flow
    'jmp' : 'pc = {0}-1',
    'jeq' : 'pc = {0}-1 if {1} == {2} else pc',
    'jne' : 'pc = {0}-1 if {1} != {2} else pc',
    'jgt' : 'pc = {0}-1 if {1} >  {2} else pc',
    'jlt' : 'pc = {0}-1 if {1} <  {2} else pc',
    'jge' : 'pc = {0}-1 if {1} >= {2} else pc',
    'jle' : 'pc = {0}-1 if {1} <= {2} else pc',
    'jz'  : 'pc = {0}-1 if {1} == 0 else pc',
    'jnz' : 'pc = {0}-1 if {1} != 0 else pc',

    # I/O
    'print'   : 'print({0})',
    'println' : 'print({0}, end="")',
    'input'   : '{0} = input("{1}")',
    'clear'   : 'print("\033[H\033[J", end="")',
    'halt'    : 'running = False',
    '--'      : 'pass',

    # Graphics
    'draw_bg'    : 'screen.fill(({0}, {1}, {2}))',
    'draw_rect'  : 'pygame.draw.rect(screen, ({4},{5},{6}), ({0}, {1}, {2}, {3}))',
    'draw_circ'  : 'pygame.draw.circle(screen, ({3},{4},{5}), ({0}, {1}), {2})',
    'update'     : 'pygame.display.flip()',
    'get_mouse'  : '{0}, {1} = pygame.mouse.get_pos()',
    'get_click'  : '{0}, {1}, {2} = pygame.mouse.get_pressed()',
    'get_scroll' : '{0} = next((event.y for event in pygame.event.get(pygame.MOUSEWHEEL)), 0)',
    'get_press'  : 'exec("if pygame.key.get_pressed()[pygame."+{1}+"]: {0}=1")',
    'draw_line'  : 'pygame.draw.line(screen, ({5},{6},{7}), ({0}, {1}), ({2}, {3}), {4})',
    'draw_text'  : 'screen.blit(pygame.font.SysFont("Arial", {3}).render(str({0}), True, ({4},{5},{6})), ({1},{2}))',
    'draw_tri'   : 'pygame.draw.polygon(screen, ({6},{7},{8}), (({0},{1}),({2},{3}),({4},{5})))',
    'sound'      : 'import numpy as np, pygame; pygame.mixer.init() if not pygame.mixer.get_init() else None; d={2};a={3};c={4};s={5};r={6};sr=44100; t=np.linspace(0,d,int(sr*d)); sus=max(0,d-a-c-r); env=np.concatenate([np.linspace(0,1,int(sr*a)),np.linspace(1,s,int(sr*c)),np.full(int(sr*sus),s),np.linspace(s,0,int(sr*r))]); wave=((np.sin(2*np.pi*{1}*t) if {0}=="sine" else (np.sign(np.sin(2*np.pi*{1}*t)) if {0}=="square" else ((2*np.arcsin(np.sin(2*np.pi*{1}*t))/np.pi) if {0}=="triangle" else np.random.uniform(-1,1,len(t)))))*env*32767).astype(np.int16); stereo=np.column_stack((wave[:len(env)],wave[:len(env)])); pygame.sndarray.make_sound(stereo).play()',
    'sleep'      : 'time.sleep({0})',
    'clockspeed' : 'STEPS_PER_TICK = {0}',

    # Lists / Arrays
    'list_new'    : '{0} = ast.literal_eval("["+{1}+"]")',
    'list_get'    : '{0} = {1}[{2}]',
    'list_set'    : '{0}[{1}] = {2}',
    'list_push'   : '{0}.append({1})',
    'list_pop'    : '{0}.pop()',
    'list_len'    : '{0} = {1}.len()',
    'list_slice'  : '{0} = {1}[{2}:{3}]',
    'list_insert' : '{0}.insert({1},{2})',
    'list_remove' : '{0}.remove({1})',
    'list_clear'  : '{0}.clear()',
    'list_extend' : '{0}.extend({1})',
    'list_range'  : '{0} = range({1})',

    'arr_zeros'  : '{0} = np.zeros(({1},{2}))',
    'arr_ones'   : '{0} = np.ones(({1},{2}))',
    'arr_shape'  : '{0} = np.shape({1})',
    'arr_get'    : '{0} = {1}[{2},{3}]',
    'arr_set'    : '{0}[{1},{2}] = {3}',
    'arr_fill'   : '{0}.fill({1})',
    'arr_sum'    : '{0} = np.sum({1})',
    'arr_mean'   : '{0} = np.mean({1},{2})',
    'arr_flat'   : '{0} = {1}.flatten()',
    'arr_rshape' : '{0} = {1}.reshape({2},{3})',
    'arr_rand'   : '{0} = np.random.rand({1},{2})',

    'copy' : '{0} = {1}.copy()',
}