name: Build Binaries
on: [push]

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Dependencies
        run: |
          pip install PySide6 pygame pyinstaller
      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --noconsole AsmStudio.py
      - uses: actions/upload-artifact@v4
        with:
          name: output-${{ matrix.os }}
          path: dist/